# Generated by Django 4.2.19 on 2025-02-18 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0002_products_productssubimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_Type_name', models.CharField(max_length=255)),
                ('product_Sub_type_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='product_brand_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='product_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_types', to='store_app.producttypes'),
        ),
    ]
