# Generated by Django 4.2.19 on 2025-02-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0003_producttypes_products_product_brand_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttypes',
            name='is_featured_product',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
