# Generated by Django 4.2.19 on 2025-02-18 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0004_producttypes_is_featured_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_price',
            field=models.IntegerField(null=True),
        ),
    ]
