# Generated by Django 4.2.19 on 2025-02-18 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0005_products_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_image',
            field=models.ImageField(upload_to='product_main_images/'),
        ),
        migrations.AlterField(
            model_name='productssubimage',
            name='product_subimage',
            field=models.ImageField(upload_to='product_sub_images/'),
        ),
    ]
