# Generated by Django 4.2.19 on 2025-02-28 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0006_alter_products_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_color',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
