# Generated by Django 4.2.19 on 2025-02-28 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0008_rename_producttypes_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='category_image',
            field=models.ImageField(null=True, upload_to='category_image/'),
        ),
    ]
