# Generated by Django 4.2.19 on 2025-02-28 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0009_categories_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='URL',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
