# Generated by Django 4.2.19 on 2025-03-04 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0011_brands'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brands',
        ),
    ]
