# Generated by Django 4.2.19 on 2025-03-09 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0012_delete_brands'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='address',
        ),
    ]
