# Generated by Django 4.2.19 on 2025-03-21 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0016_products_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_quantity',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
    ]
