# Generated by Django 4.2.19 on 2025-03-25 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0017_alter_products_product_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='product_price',
            new_name='unit_product_price',
        ),
    ]
