# Generated by Django 4.2.19 on 2025-03-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0018_rename_product_price_products_unit_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product_total_price',
            field=models.IntegerField(null=True),
        ),
    ]
