# Generated by Django 4.2.19 on 2025-04-09 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0019_cart_product_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_total_price',
            field=models.IntegerField(null=True),
        ),
    ]
