# Generated by Django 4.2.19 on 2025-05-06 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0021_payment_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment_history',
            name='receipt_url',
        ),
        migrations.RemoveField(
            model_name='payment_history',
            name='stripe_payment_intent',
        ),
    ]
