# Generated by Django 4.2.19 on 2025-05-09 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0022_remove_payment_history_receipt_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment_history',
            name='timestamp',
        ),
    ]
