# Generated by Django 4.2.19 on 2025-05-10 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0023_remove_payment_history_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='product_Sub_type_name',
        ),
    ]
