# Generated by Django 4.2.19 on 2025-05-26 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0024_remove_categories_product_sub_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_history',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store_app.products'),
        ),
    ]
