# Generated by Django 4.2.19 on 2025-05-26 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0025_payment_history_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment_history',
            name='product',
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='store_app.payment_history')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.products')),
            ],
        ),
    ]
