# Generated by Django 4.2.19 on 2025-05-26 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0026_remove_payment_history_product_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price_of_purchase',
            field=models.IntegerField(null=True),
        ),
    ]
