# Generated by Django 4.2.19 on 2025-05-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0027_orderitem_price_of_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='date_of_order',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
